import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import * as React from "react";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>GT News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/GTNEWS.png" />
      </Head>
      <main className={styles.main}>
        <h1 className="title">
          <Link href="/signIn">Login test</Link>
          <br />
          <Link href="/testimport">Test creating a component</Link>
          <br />
          <Link href="/accountSettings">accountSetting</Link>
        </h1>
      </main>
    </div>
  );
}
